# Stage 0, "builder", extract fat jar
FROM amd64/openjdk:14-alpine as builder
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} /target/application.jar
RUN mkdir -p /target/dependency && (cd /target/dependency; jar -xf ../*.jar)

# Stage 1, "boot-app"
FROM amd64/openjdk:14-alpine
ENV TZ=Europe/Oslo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
COPY --from=builder /target/dependency/BOOT-INF/lib /application/lib
COPY --from=builder /target/dependency/BOOT-INF/classes /application
COPY --from=builder /target/dependency/META-INF /application
ENV CONFIG_FILE=/application/config/application.properties
ENV SMP_CLIENT_CONFIG=/config-smp-client/smp-client.properties
ENTRYPOINT ["java", "-cp" , "/application:/application/lib/*", "no.brreg.toop.Application"]
