FROM phelger/phoss-smp-xml:latest

ENV TZ=Europe/Oslo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY target/classes/config/playground-truststore-v4.1.jks /config/
COPY target/classes/config/toop-keystore.jks /config/

#Properties files are added as OpenShift secrets
ENV SMP_SERVER_CONFIG=/smp-server-secret/smp-server.properties
ENV SMP_WEBAPP_CONFIG=/webapp-secret/webapp.properties
ENV DIRECTORY_CLIENT_CONFIG=/pd-client-secret/pd-client.properties
