FROM phelger/phoss-smp-xml:snapshot

ENV TZ=Europe/Oslo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY target/classes/config/playground-truststore-v4.1.jks /config/
COPY target/classes/config/toop-keystore.jks /config/

#Properties files are added as OpenShift secrets
ENV SMP_SERVER_CONFIG=/config-smp-server/smp-server.properties
ENV SMP_WEBAPP_CONFIG=/config-webapp/webapp.properties
ENV CONFIG_FILE=/config-pd-client/pd-client.properties
